// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNQp6E31HPi16dtJ88kBqfqOqOdOjxnQ',
    appId: '1:953979522807:web:87154f774b3f673ce6cdf2',
    messagingSenderId: '953979522807',
    projectId: 'match-point-eyego',
    authDomain: 'match-point-eyego.firebaseapp.com',
    storageBucket: 'match-point-eyego.firebasestorage.app',
    measurementId: 'G-CQBB5581X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52T43_ArxhvcXSoVTJU8yFAJYgZfjjLQ',
    appId: '1:953979522807:android:b4f308dccc51e420e6cdf2',
    messagingSenderId: '953979522807',
    projectId: 'match-point-eyego',
    storageBucket: 'match-point-eyego.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6Wji-IeRy1pw3nSMrmy2pFl2aQD_gCI',
    appId: '1:953979522807:ios:bb7ee1d60f83ba43e6cdf2',
    messagingSenderId: '953979522807',
    projectId: 'match-point-eyego',
    storageBucket: 'match-point-eyego.firebasestorage.app',
    androidClientId: '953979522807-esuqpgtm10i65bpt2d3nj5r87hfskups.apps.googleusercontent.com',
    iosClientId: '953979522807-35s989ggtf5untd86s0q51tq598mmm9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyegoProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI6Wji-IeRy1pw3nSMrmy2pFl2aQD_gCI',
    appId: '1:953979522807:ios:bb7ee1d60f83ba43e6cdf2',
    messagingSenderId: '953979522807',
    projectId: 'match-point-eyego',
    storageBucket: 'match-point-eyego.firebasestorage.app',
    androidClientId: '953979522807-esuqpgtm10i65bpt2d3nj5r87hfskups.apps.googleusercontent.com',
    iosClientId: '953979522807-35s989ggtf5untd86s0q51tq598mmm9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyegoProject',
  );
}
